# install cockpit
- name: Install cockpit
  apt: 
    name: cockpit
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install cockpit
  yum:
    name: cockpit
    update_cache: yes    
  when: ansible_os_family == "RedHat"

# configure
- name: Configuration Cockpit Server
  copy:
    src: cockpit.conf
    dest: /etc/cockpit/

- name: Start & Enable cockpit
  shell: |
    systemctl restart sockpit
    systemctl enable --now cockpit.socket 

- name: Check cockpit Service
  shell: systemctl status cockpit | grep Active*
  register: check_cockpit_service
  notify: check_cockpit_service